-- ========================================
-- ANALYSIS 
-- ========================================

-- A. Revenue

-- What is the total revenue generated by bike products?

SELECT 'Bike' AS Revenue, SUM(LineTotal) AS Amount FROM dbo.sales_dataset WHERE IsBike = 1
UNION
SELECT 'Total', SUM(LineTotal) FROM dbo.sales_dataset

-- what is the average revenue per order?

SELECT 'Bike' AS AverageRevenue, AVG(LineTotal) AS Amount FROM dbo.sales_dataset WHERE IsBike = 1
UNION
SELECT 'Total', AVG(LineTotal) FROM dbo.sales_dataset

-- B. Products

-- Which bike products generate the highest revenue?

SELECT ProductName AS Category, SUM(LineTotal) AS Revenue 
FROM dbo.sales_dataset 
WHERE IsBike = 1 
GROUP BY ProductName 
ORDER By Revenue DESC

-- which bike products sell the most units?

SELECT ProductName AS Category, SUM(OrderQty) AS TotalUnitsSold 
FROM dbo.sales_dataset 
WHERE IsBike = 1 
GROUP BY ProductName 
ORDER BY TotalUnitsSold DESC

-- is revenue driven by price or quantity?

SELECT ProductName, SUM(LineTotal) AS Revenue, SUM(OrderQty) AS Quantity, AVG(UnitPrice) AS AvgPrice
FROM dbo.sales_dataset
WHERE IsBike = 1
GROUP BY ProductName
ORDER BY Revenue DESC

-- C. Clients

-- who are the top customers buiyng bikes?

SELECT TOP 10 *
FROM dbo.sales_dataset
WHERE IsBike = 1
ORDER BY LineTotal DESC

-- 

SELECT 
CustomerID,  CustomerName, SUM(LineTotal) AS TotalRevenue
FROM dbo.sales_dataset
WHERE IsBike = 1
GROUP BY CustomerID, CustomerName
ORDER BY TotalRevenue DESC

-- how concencrated is revenue across customers?

WITH Customer_Revenue AS (
SELECT 
    CustomerID,
    CustomerName,
    SUM(LineTotal) AS TotalRevenue
FROM dbo.sales_dataset
WHERE IsBike = 1
GROUP BY CustomerID, CustomerName
)

SELECT 
    CustomerID,
    CustomerName,
    TotalRevenue,
    TotalRevenue * 1.0 / SUM(TotalRevenue) OVER() AS RevenueShare
FROM Customer_Revenue
ORDER BY TotalRevenue DESC

--

SELECT 
    CustomerID, 
    CustomerName, 
    
    SUM(LineTotal) AS TotalRevenue,
    
    SUM(CASE WHEN IsBike = 1 THEN LineTotal ELSE 0 END) AS BikeRevenue

FROM dbo.sales_dataset
GROUP BY 
    CustomerID, 
    CustomerName

-- D. Location

-- which regions generate the highest bike sales?

SELECT 
CountryRegion, StateProvince, SUM(LineTotal) AS TotalRevenue,
SUM(CASE WHEN IsBike = 1 THEN LineTotal ELSE 0 END) AS BikeRevenue,
SUM(CASE WHEN IsBike = 1 THEN LineTotal ELSE 0 END) * 1.0 / SUM(LineTotal) AS BikeShare

FROM dbo.sales_dataset
GROUP BY StateProvince, CountryRegion

-- E. Promotions

-- are discounts commonly applied to bike products?

SELECT 
SUM(CASE WHEN IsBike = 1 AND UnitPriceDiscount > 0 THEN LineTotal ELSE 0 END) AS RevenueOnDiscount,
SUM(CASE WHEN IsBike = 1 AND UnitPriceDiscount > 0 THEN OrderQty ELSE 0 END ) AS CountOfBikesOnDiscount,
SUM(CASE WHEN IsBike = 1 AND UnitPriceDiscount = 0 THEN LineTotal ELSE 0 END) AS RevenueNoDiscount,
SUM(CASE WHEN IsBike = 1 AND UnitPriceDiscount = 0 THEN OrderQty ELSE 0 END) AS CountOfBikesNoDiscount
FROM dbo.sales_dataset

-- do discounted products generate more revenues?

SELECT 
    CASE 
        WHEN UnitPriceDiscount > 0 THEN 'Discount'
        ELSE 'No Discount'
    END AS DiscountType,

    SUM(LineTotal) AS Revenue,
    SUM(OrderQty) AS Units,
    AVG(UnitPrice) AS AvgPrice

FROM dbo.sales_dataset
WHERE IsBike = 1

GROUP BY 
    CASE 
        WHEN UnitPriceDiscount > 0 THEN 'Discount'
        ELSE 'No Discount'
    END